language: cpp
compiler:
  #  - gcc
  - clang
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf g++-4.8 libev-dev libevent-dev libjansson-dev libjemalloc-dev libxml2-dev libssl-dev zlib1g-dev
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - $CXX -v
env:
  - NGHTTP2_CURRENT=true
  - NGHTTP2_CURRENT=false
before_script:
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - export MRUBY_CONFIG=../mruby-http2/.travis_build_config.rb
  - mkdir -p /usr/local/trusterd/htdocs
  - echo "hello trusterd world." > /usr/local/trusterd/htdocs/index.html
script:
  - rake
  - ./bin/mruby ../mruby-http2/example/http2_server.rb
  - ./build/host/mrbgems/mruby-http2/nghttp2/src/nghttp -v http://127.0.0.1:8080/index.html
  - ./build/host/mrbgems/mruby-http2/nghttp2/src/nghttp -v https://nghttp2.org/
  - rake all test
notifications:
  webhooks:
    - secure: "fAUM6YafzwYRwGDOXkdLuQo351nj5dPkGyPFV00D9mrYkiJG2iogrEsNHZvWlE0EvtqcxmTNHUfpS21a4sW4CguviP+zeupNB9tkQz7ckgFGYjLI1fMchEgRMziAOFUjNNn9BOrrrY/6jRVdPMw3noLEeMwzIURT/s544aFvdjQ="

