language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf
env:
  - NGHTTP2_CURRENT=true
  - NGHTTP2_CURRENT=false
before_script:
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - export MRUBY_CONFIG=../mruby-http2/.travis_build_config.rb
script: 
  - rake all test
notifications:
  webhooks:
    - secure: "fAUM6YafzwYRwGDOXkdLuQo351nj5dPkGyPFV00D9mrYkiJG2iogrEsNHZvWlE0EvtqcxmTNHUfpS21a4sW4CguviP+zeupNB9tkQz7ckgFGYjLI1fMchEgRMziAOFUjNNn9BOrrrY/6jRVdPMw3noLEeMwzIURT/s544aFvdjQ="

